---
version: '2'

services:
    strongswan:
        restart: always
        image: {{ container_registry }}/contrail-datapath-encryption-strongswan:{{ contrail_version_tag }}
        network_mode: host
        privileged: true
        pid: host
        volumes:
            - "/etc/contrail/vrouter/strongswan:/etc/contrail/strongswan:ro"
            - "/var/run/:/var/run/:rw"
        command: "/usr/libexec/ipsec/starter --daemon charon --nofork"
    strongswan_api:
        restart: always
        image: {{ container_registry }}/contrail-datapath-encryption-strongswan-api:{{ contrail_version_tag }}
        network_mode: host
        privileged: true
        pid: host
        volumes:
            - "/etc/contrail/vrouter/strongswan:/etc/contrail/strongswan:rw"
            - "/var/run/:/var/run/:rw"
        command: "python /opt/contrail-ipsec/contrail_ipsec/ipsec_api.py -c /etc/contrail/strongswan/contrail-ipsec.conf"
