command_ip: {{ command_ip }}
ntpserver: time.google.com
vrouter_gateway: {{ vrouter_gateway }}
container_registry: {{ container_registry }}
container_tag: {{ container_tag }}
contrail_container_tag: {{ contrail_container_tag }}
install_docker: {{ install_docker }}
ccd_connection: local