options:
  physical-interface:
    type: string
    description: |
      Specify the interface to install vhost0 on. If left empty, vhost0 will
      be installed on the default gateway interface.
  vhost-gateway:
    type: string
    default: auto
    description: |
      Specify the gateway for vhost0, either an IPv4 address or keyword 'auto'.
      'auto' will set gateway automatically.
  dpdk:
    type: boolean
    default: false
    description: Use user space DPDK vRouter
  hostname-use-fqdn:
    type: boolean
    default: true
    description: |
      Use fqdn for vrouter_hostname or use gethostname instead.
      fqdn is used in R5.1 and in further releases.
      R5.0 releases used hostname that doesn’t always return
      the fully qualified domain name.
  dpdk-driver:
    type: string
    default: uio_pci_generic
    description: |
      DPDK driver to use for physical interface.
      Interface can be specified using vhost-interface.
  dpdk-hugepages:
    type: string
    default: 70%
    description: |
      Number of huge pages to reserve for use with DPDK vRouter and OpenStack
      instances.
      Value can be specified as percentage of system memory e.g. 70% or as
      number of huge pages e.g. 1434.
  kernel-hugepages-1g:
    type: string
    description: |
      Number of 1 GB huge pages to reserve for use with vRouter in kernel mode  and OpenStack instances.
      Value can be specified as number of huge pages e.g. 10.
      To turn off HP suppor completely kernel-hugepages-1g and kernel-hugepages-2m must be set as '0' both.
      Supported from Contrail release 2005.
  kernel-hugepages-2m:
    type: string
    default: '1024'
    description: |
      Number of 2 MB huge pages to reserve for use with vRouter in kernel mode  and OpenStack
      instances.
      Value can be specified as number of huge pages e.g. '1024'.
      To turn off HP suppor completely kernel-hugepages-1g and kernel-hugepages-2m must be set as '0' both.
      Supported from Contrail release 2005.
  dpdk-coremask:
    type: string
    default: "1"
    description: |
      vRouter CPU affinity mask for dpdk forwarding threads.
      Value can be specified as either a hexidecimal bitmask e.g. 0xF or
      as a numbered list separated by commas e.g. 0,1 (ranges are also supported
      using '-' e.g. 0-2).
      It must specify only real cores cause contrail-vrouter-dpdk service will
      fail if specified core number is not present in the system.
  dpdk-service-coremask:
    type: string
    default: "1"
    description: |
      vRouter DPDK CPU affinity mask for dpdk service threads.
      Value can be specified as either a hexidecimal bitmask e.g. 0xF or
      as a numbered list separated by commas e.g. 0,1 (ranges are also supported
      using '-' e.g. 0-2).
      It must specify only real cores cause contrail-vrouter-dpdk service will
      fail if specified core number is not present in the system.
      Supported from Contrail release 2003 and R1912.L2.
  dpdk-ctrl-thread-coremask:
    type: string
    default: "1"
    description: |
      vRouter DPDK CPU affinity mask for dpdk ctrl threads.
      Value can be specified as either a hexidecimal bitmask e.g. 0xF or
      as a numbered list separated by commas e.g. 0,1 (ranges are also supported
      using '-' e.g. 0-2).
      It must specify only real cores cause contrail-vrouter-dpdk service will
      fail if specified core number is not present in the system.
      Supported from Contrail release 2003 and R1912.L2.
  dpdk-rx-ring-sz:
    type: string
    default: ""
    description: |
      vRouter DPDK option to configure for forwarding lcores rx ring buffer size.
      If not there is default in dpdk bin is used which is 1024.
      Supported from Contrail release 2003 and R1912.L2.
  dpdk-tx-ring-sz:
    type: string
    default: ""
    description: |
      vRouter DPDK option to configure for forwarding lcores tx ring buffer size.
      If not there is default in dpdk bin is used which is 1024.
      Supported from Contrail release 2003 and R1912.L2.
  dpdk-yield-option:
    type: string
    default: ""
    description: |
      vRouter DPDK option to disable/enable yield on forwarding lcores.
      Allowed values 0 / 1.
      If not set the default behaviour is enalbed (1).
      Supported from Contrail release 2003 and R1912.L2.
  dpdk-main-mempool-size:
    type: string
    description: |
      Main packet pool size.
  dpdk-pmd-txd-size:
    type: string
    description: |
      DPDK PMD Tx Descriptor size.
  dpdk-pmd-rxd-size:
    type: string
    description: |
      DPDK PMD Rx Descriptor size.
  sriov-physical-interface:
    type: string
    description: |
      A comma-separated list of interface names for SR-IOV.
      The number of elements in the list should be equal to number of elements in sriov-numvfs.
      List is supported only by R2008 release and further.
      For previous releases only first element will be taken.
      This parameter and sriov-numvfs will be passed into agent container that will configure SR-IOV.
  sriov-numvfs:
    type: string
    description: |
      A comma-separated list of NumVFS's for specified devices.
      The number of elements in the list should be equal to number of elements in sriov-physical-interface.
      List is supported only by R2008 release and further.
      For previous releases only first element will be taken.
      This parameter and sriov-physical-interface will be passed into agent container that will configure SR-IOV.
  csn-mode:
    type: string
    description: |
      The vrouter agent mode. The valid values are 'tor'/'tsn'/'tsn-no-forwarding' or empty.
    default: ''
  datapath-encryption:
    type: boolean
    default: false
    description: Use datapath encryption between vRouters.
  log-level:
    type: string
    default: SYS_NOTICE
    description: |
      Log level for contrail services. Valid values are:
      SYS_EMERG, SYS_ALERT, SYS_CRIT, SYS_ERR, SYS_WARN, SYS_NOTICE, SYS_INFO, SYS_DEBUG
  docker_runtime:
    type: string
    default: upstream
    description: |
      Docker runtime to install valid values are "upstream" (Docker PPA), "apt" (Ubuntu archive),
      "auto" (Ubuntu archive), or "custom" (must have set `docker_runtime_repo` URL,
      `docker_runtime_key_url` URL and `docker_runtime_package` name).
      Warning! The changes will not be applied after the package is installed.
  docker_runtime_key_url:
    type: string
    description: |
      Custom Docker repository validation key URL.
      Warning! The changes will not be applied after the package is installed.
  docker_runtime_package:
    type: string
    description: |
      Custom Docker repository package name.
      Warning! The changes will not be applied after the package is installed.
  docker_runtime_repo:
    type: string
    description: |
      Custom Docker repository, given in deb format. Use `{ARCH}` to determine architecture at runtime.
      Use `{CODE}` to set release codename.
      E.g. `deb [arch={ARCH}] https://download.docker.com/linux/ubuntu {CODE} stable`.
      Warning! The changes will not be applied after the package is installed.
  docker-registry:
    type: string
    default: opencontrailnightly
    description: |
      URL of docker-registry
  docker-registry-insecure:
    type: boolean
    default: false
    description: |
      Is it docker-registry insecure and should docker be configured for it
  docker-opts:
    type: string
    description: |
      Extra options to pass to the Docker config file '/etc/docker/daemon.json' in json format.
      e.g. {"iptables": false, "insecure-registries": ["host2", "tungstenfabric", "host1"]}
  docker-user:
    type: string
    description: |
      Login to the docker registry.
  docker-password:
    type: string
    description: |
      Password to the docker registry.
  docker-log-driver:
    type: string
    default: json-file
    description: |
      A logging driver for the service’s containers.
  docker-log-options:
    type: string
    default: "max-size=20m max-file=5"
    description: |
      Logging options for the logging driver. Logging options available depend
      on which logging driver you use.
  image-tag:
    type: string
    default: latest
    description: |
      Tag of docker image.
  http_proxy:
    type: string
    default: ""
    description: |
      URL to use for HTTP_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
  https_proxy:
    type: string
    default: ""
    description: |
      URL to use for HTTPS_PROXY to be used by Docker. Only useful in closed
      environments where a proxy is the only option for routing to the
      registry to pull images
  no_proxy:
    type: string
    default: ""
    description: |
      Comma-separated list of destinations (either domain names or IP
      addresses) that should be directly accessed, by opposition of going
      through the proxy defined above. Must be less than 2023 characters long
  wait-for-external-plugin:
    type: boolean
    default: false
    descripton: |
      Enable external vRouter datapath plugin. This can be used with the agilio-vrouter
      charm to enable a hardware offloaded vRouter datapath.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  max-vm-flows:
    default: ""
    type: string
    description: |
      Maximum flows allowed per VM (given as % of maximum system flows) 
