#!/bin/bash
# Wrapper to deal with newer Ubuntu versions that don't have py2 installed
# by default.

declare -a DEPS=('apt' 'netaddr' 'netifaces' 'pip' 'yaml' 'dnspython' 'jinja2')

check_and_install() {
    pkg="${1}-${2}"
    if ! dpkg -s ${pkg} 2>&1 > /dev/null; then
        apt-get -y install ${pkg}
    fi
}

PYTHON="python3"

for dep in ${DEPS[@]}; do
    check_and_install ${PYTHON} ${dep}
done

# special case for vrouter-port-control wich still have /usr/bin/python in shebang
apt-get -y install python-is-python3

exec ./hooks/install.real
