#!/bin/bash
# Wrapper to deal with newer Ubuntu versions that don't have py2 installed
# by default.

declare -a DEPS=('apt' 'netaddr' 'netifaces' 'pip' 'yaml' 'dnspython' 'iproute' 'backports.ssl-match-hostname')

check_and_install() {
    pkg="${1}-${2}"
    if ! dpkg -s ${pkg} 2>&1 > /dev/null; then
        apt-get -y install ${pkg}
    fi
}

PYTHON="python"

for dep in ${DEPS[@]}; do
    check_and_install ${PYTHON} ${dep}
done

apt -y install sshpass docker
pip install ansible==2.7.11
cp -r /usr/lib/python2.7/dist-packages/backports/ssl_match_hostname /usr/local/lib/python2.7/dist-packages/backports/

exec ./hooks/install.real
